### ISSUE TITLE
Backend /module get is returning server error (500)

### ISSUE THREAD

**Issue by rzaracota** [CSS566-Spring2018/CSS566CoursesProject#15]
This issue is occurring even with 17227 which was working the other day.

**Comment by mitchl2** [comment]
Taking a look, I'll keep you posted

**Comment by mitchl2** [comment]
The fix is pending a merge request: https://github.com/CSS566-Spring2018/CSS566CoursesProject/pull/16

**Comment by rzaracota** [comment]
Confirmed. Thanks all.
